repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: flake8

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
      - id: reorder-python-imports
        python_version: python3.7

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        python_version: python3.7

  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.610-1
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
